services:
  tgprism:
    build: .
    container_name: tgprism
    restart: always
    ports:
      - "${SERVER_PORT:-8000}:${SERVER_PORT:-8000}"
    volumes:
      - ./sessions:/app/sessions
      - ./prism.db:/app/prism.db
    environment:
      - LOG_LEVEL
      - PROXY_TYPE
      - SERVER_PORT
      - SINGBOX_SUB
      - API_ID
      - API_HASH